services:
  mongodb:
    image: mongo
    container_name: ecommerce-mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
      - ./infra/mongo/.env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: